/**
 * Firefox Preferences
 *
 * This module provides a centralized way to manage Firefox profile preferences.
 */

/**
 * Returns the default Firefox preferences as a string
 *
 * @param {Object} options - Optional configuration options
 * @param {boolean} options.enableProxy - Whether to enable proxy
 * @param {string} options.proxyHost - Proxy host address
 * @param {number} options.proxyPort - Proxy port number
 * @param {boolean} options.enableAutoConfig - Whether to enable AutoConfig for extension autoload
 * @returns {string} Firefox preferences as a string
 */
function getDefaultPreferences(options = {}) {
  const prefs = [
    // Basic browser settings
    "user_pref(\"browser.shell.checkDefaultBrowser\", false);",
    "user_pref(\"browser.startup.homepage\", \"about:blank\");",
    "user_pref(\"browser.startup.page\", 0);",
    "user_pref(\"browser.tabs.warnOnClose\", false);",
    "user_pref(\"browser.tabs.warnOnOpen\", false);",
    "user_pref(\"browser.sessionstore.resume_from_crash\", false);",
    "user_pref(\"browser.newtabpage.enabled\", false);",
    "user_pref(\"browser.aboutConfig.showWarning\", false);",

    // Theme and appearance
    "user_pref(\"ui.systemUsesDarkTheme\", 0);", // Disable dark mode

    // Telemetry and reporting
    "user_pref(\"datareporting.healthreport.service.enabled\", false);",
    "user_pref(\"datareporting.healthreport.uploadEnabled\", false);",
    "user_pref(\"datareporting.policy.dataSubmissionEnabled\", false);",
    "user_pref(\"toolkit.telemetry.reportingpolicy.firstRun\", false);",
    "user_pref(\"toolkit.telemetry.enabled\", false);",
    "user_pref(\"toolkit.telemetry.server\", \"\");",
    "user_pref(\"app.shield.optoutstudies.enabled\", false);",

    // Extensions and features
    "user_pref(\"extensions.webextensions.uiTour.enabled\", false);",
    "user_pref(\"browser.translations.automaticallyPopup\", false);",
    "user_pref(\"xpinstall.signatures.required\", false);",
    "user_pref(\"extensions.install.requireBuiltInCerts\", false);",
    "user_pref(\"extensions.autoDisableScopes\", 0);",
    "user_pref(\"extensions.webextensions.remote\", false);",
    "user_pref(\"extensions.langpacks.signatures.required\", false);",
  ];

  // Add AutoConfig settings for extension autoload if enabled
  if (options.enableAutoConfig) {
    prefs.push(...[
      "// AutoConfig settings for automatic extension loading",
      // Disable the sandbox to enable running unsafe code
      "user_pref(\"general.config.sandboxLevel\", 0);",
      "user_pref(\"general.config.sandbox_enabled\", false);",
      // The file named in the following line must be in [Firefox program folder]
      "user_pref(\"general.config.filename\", \"userChrome.js\");",
      "user_pref(\"general.config.obscure_value\", 0);"

    ]);
  }

  // Add proxy settings if needed
  if (options.enableProxy && options.proxyHost && options.proxyPort) {
    prefs.push(...[
      "user_pref(\"network.proxy.type\", 1);", // Manual proxy configuration
      `user_pref(\"network.proxy.http\", \"${options.proxyHost}\");`,
      `user_pref(\"network.proxy.http_port\", ${options.proxyPort});`,
      `user_pref(\"network.proxy.ssl\", \"${options.proxyHost}\");`,
      `user_pref(\"network.proxy.ssl_port\", ${options.proxyPort});`,
      `user_pref(\"network.proxy.ftp\", \"${options.proxyHost}\");`,
      `user_pref(\"network.proxy.ftp_port\", ${options.proxyPort});`,
      `user_pref(\"network.proxy.socks\", \"${options.proxyHost}\");`,
      `user_pref(\"network.proxy.socks_port\", ${options.proxyPort});`,
      "user_pref(\"network.proxy.share_proxy_settings\", true);", // Use the same proxy for all protocols
      "user_pref(\"network.proxy.no_proxies_on\", \"localhost, 127.0.0.1\");"
    ]);
  }

  return "// Mozilla User Preferences\n// Generated by BSYNC Firefox extension\n\n" + prefs.join("\n");
}

module.exports = {
  getDefaultPreferences
}; 